### ISSUE TITLE
Running on Colab

### ISSUE THREAD

**Issue by BiaBibii** [ardaduz/deep-video-mvs#14]
Hello, I'm trying to run this code in google colab, and I get this error.
I tried to use imageio, skimage instead of cv2.imread, but it doesn't work.
Thanks

!python run-testing-online.py

> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

**Comment by catalinbotean** [comment]
@BiaBibii Facing the same problem

**Comment by ardaduz** [comment]
Hi,

The error you're getting is not related to how we load images, i.e., it is not about `cv2.imread`. Rather, it is about how we visualize the depth predictions while running `run-testing-online.py`. `visualize_predictions` [here](https://github.com/ardaduz/deep-video-mvs/blob/master/dvmvs/fusionnet/run-testing-online.py#L217), calls `cv2.imshow` function [here](https://github.com/ardaduz/deep-video-mvs/blob/fa14288f149c5af7b2a49092f729f5c4f44517ba/dvmvs/utils.py#L363), which uses Qt backend to open a GUI window to show the depth predictions. This requires some kind of physical display connection and/or X server which Google Colab machines naturally do not have. There are many threads on the same problem you're facing such as [this one](https://stackoverflow.com/questions/64113537/google-colab-error-could-not-load-the-qt-platform-plugin-xcb) or [this one](https://stackoverflow.com/questions/56491808/could-not-connect-to-any-x-display-google-colab-run-time).

Now that we've established the reason, let's discuss the solution. You can set `Config.test_visualize=False` [here](https://github.com/ardaduz/deep-video-mvs/blob/fa14288f149c5af7b2a49092f729f5c4f44517ba/dvmvs/config.py#L28), which disables the visualization.

If you have to use Google Colab and if you want to look at the depth predictions, I can suggest two things:
1. The predictions are already being saved to an .npz file [in this function](https://github.com/ardaduz/deep-video-mvs/blob/master/dvmvs/fusionnet/run-testing-online.py#L227). Download this .npz file to your local machine that has a screen, and write a piece of code that goes through the predictions and shows them.
2. Modify the code slightly to use `cv2.imwrite` to save the predictions as PNG images somewhere on Google Drive, so that you can visually inspect them later.
